import type { Biome, BuildingDefinition, BuildingKey, EnemyDefinition, EnemyKey, Resources, Terrain } from "./gameTypes";

export const GAME_VERSION = "0.1.0-pr1";
export const MAP_WIDTH = 96;
export const MAP_HEIGHT = 64;
export const TILE_SIZE = 32;
export const VICTORY_DAY = 30;

export const BIOMES: Biome[] = ["ruinedIndustrial", "swamp", "housingRuins", "wasteland", "mountainResource"];
export const RESOURCE_KEYS = [
  "money",
  "debt",
  "interestRate",
  "iron",
  "scrap",
  "ammo",
  "fuel",
  "power",
  "population",
  "happiness",
  "taxRisk",
  "research",
  "gachaCurrency",
] as const;

export const STARTING_RESOURCES: Resources = {
  money: 1800,
  debt: 4200,
  interestRate: 0.035,
  iron: 80,
  scrap: 160,
  ammo: 80,
  fuel: 60,
  power: 35,
  population: 42,
  happiness: 58,
  taxRisk: 24,
  research: 0,
  gachaCurrency: 120,
};

export const ZERO_RESOURCES: Resources = Object.fromEntries(RESOURCE_KEYS.map((key) => [key, 0])) as Resources;

export const TERRAIN_MOVE_COST: Record<Terrain, number> = {
  plain: 1,
  road: 0.55,
  forest: 1.6,
  water: Number.POSITIVE_INFINITY,
  rock: Number.POSITIVE_INFINITY,
  ironOre: 1.35,
  oilField: 1.25,
  scrapHeap: 1.35,
};

const buildableGround: Terrain[] = ["plain", "road", "forest", "ironOre", "oilField", "scrapHeap"];
const cityGround: Terrain[] = ["plain", "road"];

export const BUILDING_DEFINITIONS: Record<BuildingKey, BuildingDefinition> = {
  HQ: {
    key: "HQ",
    nameJa: "本社",
    descriptionJa: "破壊されると敗北。破産説明会の会場でもある。",
    cost: {},
    upkeep: {},
    produces: { money: 18, research: 1 },
    maxHp: 2400,
    blocksPath: true,
    buildable: false,
    allowedTerrain: cityGround,
  },
  Road: {
    key: "Road",
    nameJa: "道路",
    descriptionJa: "物流・住民・敵の移動コストに影響する。",
    cost: { money: 8, scrap: 4 },
    upkeep: {},
    produces: {},
    maxHp: 120,
    blocksPath: false,
    buildable: true,
    allowedTerrain: buildableGround,
  },
  Wall: {
    key: "Wall",
    nameJa: "壁",
    descriptionJa: "敵を遮る。完全封鎖は強いペナルティ。",
    cost: { money: 45, scrap: 18 },
    upkeep: { money: 1 },
    produces: {},
    maxHp: 720,
    blocksPath: true,
    buildable: true,
    allowedTerrain: buildableGround,
  },
  GunTurret: {
    key: "GunTurret",
    nameJa: "砲台",
    descriptionJa: "弾薬を消費して攻撃する基本防衛施設。",
    cost: { money: 160, scrap: 80, iron: 30 },
    upkeep: { money: 4 },
    produces: {},
    maxHp: 420,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
    attack: { damage: 36, range: 6, intervalMs: 850, consumes: { ammo: 1 }, priority: "closestToHQ" },
  },
  LaserTurret: {
    key: "LaserTurret",
    nameJa: "レーザー塔",
    descriptionJa: "電力で攻撃する。停電時は高級な棒。",
    cost: { money: 260, iron: 70, research: 8 },
    upkeep: { money: 8 },
    produces: {},
    maxHp: 360,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
    attack: { damage: 58, range: 7, intervalMs: 1200, consumes: { power: 2 }, priority: "highestThreat" },
  },
  FlameTurret: {
    key: "FlameTurret",
    nameJa: "火炎放射塔",
    descriptionJa: "燃料を消費し範囲攻撃する。",
    cost: { money: 220, iron: 45, fuel: 20 },
    upkeep: { money: 6 },
    produces: {},
    maxHp: 380,
    blocksPath: true,
    buildable: true,
    allowedTerrain: ["plain", "road", "oilField"],
    attack: { damage: 22, range: 4, intervalMs: 700, consumes: { fuel: 1 }, splashRadius: 1.5, priority: "nearest" },
  },
  Miner: {
    key: "Miner",
    nameJa: "採掘機",
    descriptionJa: "鉄鉱床や廃材山から資源を生む。",
    cost: { money: 180, scrap: 75 },
    upkeep: { money: 5, power: 1 },
    produces: { iron: 8, scrap: 4 },
    maxHp: 300,
    blocksPath: true,
    buildable: true,
    allowedTerrain: ["ironOre", "scrapHeap"],
    supply: { requires: { power: 1 } },
  },
  Factory: {
    key: "Factory",
    nameJa: "工場",
    descriptionJa: "鉄や廃材から弾薬を生産する。",
    cost: { money: 260, iron: 70, scrap: 110 },
    upkeep: { money: 8, power: 3 },
    produces: { ammo: 10 },
    maxHp: 420,
    blocksPath: true,
    buildable: true,
    allowedTerrain: ["plain", "road", "scrapHeap"],
    supply: { requires: { power: 3, iron: 2, scrap: 2 } },
  },
  PowerPlant: {
    key: "PowerPlant",
    nameJa: "発電所",
    descriptionJa: "燃料または維持費で電力を生む。",
    cost: { money: 280, iron: 80, fuel: 25 },
    upkeep: { money: 10, fuel: 2 },
    produces: { power: 18, taxRisk: 1 },
    maxHp: 480,
    blocksPath: true,
    buildable: true,
    allowedTerrain: ["plain", "road", "oilField"],
    supply: { provides: { power: 18 } },
  },
  Battery: {
    key: "Battery",
    nameJa: "蓄電池",
    descriptionJa: "電力を貯める。",
    cost: { money: 130, iron: 45 },
    upkeep: { money: 2 },
    produces: {},
    maxHp: 260,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
    supply: { storage: { power: 30 } },
  },
  Conveyor: {
    key: "Conveyor",
    nameJa: "コンベア",
    descriptionJa: "PR1では簡易物流ネットワークとして描画・供給補助する。",
    cost: { money: 22, scrap: 12 },
    upkeep: { money: 1 },
    produces: {},
    maxHp: 120,
    blocksPath: false,
    buildable: true,
    allowedTerrain: buildableGround,
    supply: { logisticRadius: 4 },
  },
  House: {
    key: "House",
    nameJa: "住宅",
    descriptionJa: "収益・人口・幸福度に影響する。",
    cost: { money: 110, scrap: 45 },
    upkeep: { money: 3, power: 1 },
    produces: { money: 18, population: 4, happiness: 1 },
    maxHp: 260,
    blocksPath: true,
    buildable: true,
    allowedTerrain: ["plain", "road", "forest"],
  },
  Shop: {
    key: "Shop",
    nameJa: "商業施設",
    descriptionJa: "収益を生むが敵ヘイトと税務リスクを上げる。",
    cost: { money: 190, scrap: 65 },
    upkeep: { money: 5, power: 2 },
    produces: { money: 35, taxRisk: 2 },
    maxHp: 280,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
  },
  TaxOffice: {
    key: "TaxOffice",
    nameJa: "税務署",
    descriptionJa: "税収が上がり幸福度が下がる。ログがふざける。",
    cost: { money: 240, iron: 40 },
    upkeep: { money: 7, power: 2 },
    produces: { money: 48, happiness: -3, taxRisk: -1 },
    maxHp: 360,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
  },
  LoanOffice: {
    key: "LoanOffice",
    nameJa: "闇金融オフィス",
    descriptionJa: "即時資金を得るが借金と利息が増える。",
    cost: { money: 80, scrap: 20 },
    upkeep: { money: 4 },
    produces: { money: 120, debt: 90, interestRate: 0.002, happiness: -1 },
    maxHp: 240,
    blocksPath: true,
    buildable: true,
    allowedTerrain: cityGround,
  },
};

export const ENEMY_DEFINITIONS: Record<EnemyKey, EnemyDefinition> = {
  DebtCollector: {
    key: "DebtCollector",
    nameJa: "借金取り",
    descriptionJa: "標準敵。本社を狙う。",
    maxHp: 110,
    speedTilesPerSecond: 1.55,
    damage: 32,
    threat: 3,
    preferredTargets: ["HQ"],
    bounty: { money: 18, research: 1 },
  },
  TaxInspector: {
    key: "TaxInspector",
    nameJa: "税務調査官",
    descriptionJa: "商業施設を狙う。税務リスクが高いほど出やすい。",
    maxHp: 145,
    speedTilesPerSecond: 1.25,
    damage: 44,
    threat: 5,
    preferredTargets: ["Shop", "TaxOffice", "HQ"],
    bounty: { money: 28, research: 2, taxRisk: -1 },
  },
  Rioter: {
    key: "Rioter",
    nameJa: "暴徒",
    descriptionJa: "幸福度が低いと出やすく、住宅を狙う。",
    maxHp: 95,
    speedTilesPerSecond: 1.85,
    damage: 26,
    threat: 4,
    preferredTargets: ["House", "HQ"],
    bounty: { money: 12 },
  },
  CorporateSpy: {
    key: "CorporateSpy",
    nameJa: "企業スパイ",
    descriptionJa: "工場や発電所を狙う高速敵。",
    maxHp: 80,
    speedTilesPerSecond: 2.45,
    damage: 38,
    threat: 6,
    preferredTargets: ["Factory", "PowerPlant", "HQ"],
    bounty: { money: 22, research: 3 },
  },
  ArmoredComplainer: {
    key: "ArmoredComplainer",
    nameJa: "重装クレーマー",
    descriptionJa: "高HPで遅い。",
    maxHp: 420,
    speedTilesPerSecond: 0.7,
    damage: 95,
    threat: 8,
    preferredTargets: ["Wall", "HQ"],
    bounty: { money: 70, scrap: 18 },
  },
  BankruptcyTrusteeBoss: {
    key: "BankruptcyTrusteeBoss",
    nameJa: "破産管財人",
    descriptionJa: "数日ごとに出現。借金が多いほど強くなる。",
    maxHp: 1800,
    speedTilesPerSecond: 0.62,
    damage: 360,
    threat: 20,
    preferredTargets: ["HQ"],
    bounty: { money: 400, research: 35, gachaCurrency: 80 },
  },
};
